_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide

  column-sizes:
    col-12: celá-šířka
    col-6_sm-12: polovina
    col-4_sm-12: třetina
    col-3_sm-12: čtvrtina
    col-2_sm-12: pětina
  

   





  